export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE : 'CHANGE_PASSWORD_FAILURE',

    GET_FIRST_REQUEST : 'GET_FIRST_REQUEST',
    GET_FIRST_SUCCESS : 'GET_FIRST_SUCCESS',
    GET_FIRST_FAILURE : 'GET_FIRST_FAILURE',

    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    SUBMIT__PREV_STATION_REQUEST: 'SUBMIT__PREV_STATION_REQUEST',
    SUBMIT__PREV_STATION_SUCCESS: 'SUBMIT__PREV_STATION_SUCCESS',
    SUBMIT__PREV_STATION_FAILURE: 'SUBMIT__PREV_STATION_FAILURE'
};
